<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Print Report - <?= ucfirst($_GET['type'] ?? 'General') ?></title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #eee; }
        .header h1 { margin: 0 0 5px 0; font-size: 24px; text-transform: uppercase; letter-spacing: 1px; }
        .header p { margin: 0; color: #666; font-size: 14px; }
        
        .meta-info { display: flex; justify-content: space-between; margin-bottom: 30px; font-size: 12px; color: #555; }
        
        table { w-full; width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 30px; }
        th { text-align: left; border-bottom: 2px solid #333; padding: 10px 5px; text-transform: uppercase; font-size: 11px; }
        td { border-bottom: 1px solid #eee; padding: 10px 5px; }
        
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        
        .summary-box { float: right; width: 300px; background: #f9f9f9; padding: 15px; border: 1px solid #eee; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 5px; }
        .summary-row.total { border-top: 2px solid #333; margin-top: 10px; padding-top: 10px; font-weight: bold; font-size: 14px; }
        
        .footer { clear: both; margin-top: 50px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        
        @media print {
            body { padding: 0; }
            button { display: none; }
        }
    </style>
</head>
<body>

    <!-- PRINT CONTROL -->
    <div style="text-align: right; margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #333; color: white; border: none; cursor: pointer;">Print Report</button>
    </div>

    <!-- HEADER -->
    <div class="header">
        <h1><?= ucfirst($_GET['type'] ?? 'General') ?> Report</h1>
        <p>AREATIVE SHOP - MANAGEMENT SYSTEM</p>
    </div>

    <!-- META INFO -->
    <div class="meta-info">
        <div>
            <strong>Report Date:</strong> <?= date('F d, Y') ?><br>
            <strong>Generated By:</strong> Administrator
        </div>
        <div class="text-right">
            <strong>Period:</strong> <?= date('M d, Y', strtotime($startDate)) ?> — <?= date('M d, Y', strtotime($endDate)) ?>
        </div>
    </div>

    <!-- ======================================================= -->
    <!-- 1. SALES REPORT VIEW -->
    <!-- ======================================================= -->
    <?php if(isset($_GET['type']) && $_GET['type'] === 'sales'): ?>
        
        <!-- Top Products Table -->
        <h3>Top Selling Products</h3>
        <table>
            <thead>
                <tr>
                    <th style="width: 50px;">#</th>
                    <th>Product Name</th>
                    <th class="text-center">Units Sold</th>
                    <th class="text-right">Revenue Generated</th>
                </tr>
            </thead>
            <tbody>
                <?php if(empty($topProducts)): ?>
                    <tr><td colspan="4" class="text-center">No sales data found for this period.</td></tr>
                <?php else: ?>
                    <?php foreach($topProducts as $i => $p): ?>
                    <tr>
                        <td><?= $i + 1 ?></td>
                        <td><?= htmlspecialchars($p['name']) ?></td>
                        <td class="text-center"><?= $p['sold'] ?></td>
                        <td class="text-right"><?= number_format($p['revenue']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>

    <!-- ======================================================= -->
    <!-- 2. INVENTORY (STOCK) REPORT VIEW -->
    <!-- ======================================================= -->
    <?php elseif(isset($_GET['type']) && $_GET['type'] === 'inventory'): ?>
        
        <!-- Retrieve All Inventory for Printing -->
        <?php 
            // Fetch inventory explicitly for this view since controller passed $lowStockItems primarily
            $db = new Database();
            $conn = $db->getConnection();
            $inventory = $conn->query("SELECT name, stock, price, (stock * price) as value FROM products WHERE type='physical' ORDER BY stock ASC")->fetchAll();
            $totalStockValue = 0;
            foreach($inventory as $i) $totalStockValue += $i['value'];
        ?>

        <div style="margin-bottom: 20px;">
            <strong>Total Inventory Value:</strong> <?= number_format($totalStockValue) ?> MMK
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 50px;">#</th>
                    <th>Product Name</th>
                    <th class="text-right">Unit Price</th>
                    <th class="text-center">Current Stock</th>
                    <th class="text-right">Stock Value</th>
                    <th class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($inventory as $idx => $item): ?>
                <tr>
                    <td><?= $idx + 1 ?></td>
                    <td><?= htmlspecialchars($item['name']) ?></td>
                    <td class="text-right"><?= number_format($item['price']) ?></td>
                    <td class="text-center font-bold"><?= $item['stock'] ?></td>
                    <td class="text-right"><?= number_format($item['value']) ?></td>
                    <td class="text-center">
                        <?php if($item['stock'] <= 5): ?>
                            <span style="background: #ffebee; color: #c62828; padding: 2px 6px; font-size: 10px; font-weight: bold;">LOW</span>
                        <?php else: ?>
                            <span style="color: #2e7d32; font-size: 10px;">OK</span>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    <!-- ======================================================= -->
    <!-- 3. PURCHASE REPORT VIEW -->
    <!-- ======================================================= -->
    <?php elseif(isset($_GET['type']) && $_GET['type'] === 'purchase'): ?>
        
        <?php 
            // Fetch detailed purchases
            $db = new Database();
            $conn = $db->getConnection();
            $purchaseList = $conn->query("
                SELECT p.created_at, s.name as supplier, pr.name as product, pi.quantity, pi.cost 
                FROM purchases p
                JOIN suppliers s ON p.supplier_id = s.id
                JOIN purchase_items pi ON p.id = pi.purchase_id
                JOIN products pr ON pi.product_id = pr.id
                WHERE DATE(p.created_at) BETWEEN '$startDate' AND '$endDate'
                ORDER BY p.created_at DESC
            ")->fetchAll();
        ?>

        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Supplier</th>
                    <th>Product</th>
                    <th class="text-center">Qty</th>
                    <th class="text-right">Cost</th>
                </tr>
            </thead>
            <tbody>
                <?php if(empty($purchaseList)): ?>
                    <tr><td colspan="5" class="text-center">No purchases made in this period.</td></tr>
                <?php else: ?>
                    <?php $totalCost = 0; ?>
                    <?php foreach($purchaseList as $pur): $totalCost += $pur['cost']; ?>
                    <tr>
                        <td><?= date('Y-m-d', strtotime($pur['created_at'])) ?></td>
                        <td><?= htmlspecialchars($pur['supplier']) ?></td>
                        <td><?= htmlspecialchars($pur['product']) ?></td>
                        <td class="text-center"><?= $pur['quantity'] ?></td>
                        <td class="text-right"><?= number_format($pur['cost']) ?></td>
                    </tr>
                    <?php endforeach; ?>
                    <!-- Total Row -->
                    <tr>
                        <td colspan="4" class="text-right font-bold" style="border-top: 2px solid #333;">TOTAL SPENT</td>
                        <td class="text-right font-bold" style="border-top: 2px solid #333;"><?= number_format($totalCost) ?></td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>

    <?php endif; ?>

    <div class="footer">
        &copy; <?= date('Y') ?> Areative Shop. All rights reserved.<br>
        This is a computer-generated document. No signature is required.
    </div>

    <script>
        // Auto print when opened
        window.onload = function() { window.print(); }
    </script>
</body>
</html>